* Features

Based on w3m 0.5.3, add the following features:

+ support user defined user-agent
+ support load cookie from local file(not ~/.w3m/cookie), the format of the file is same as curl and wget (Netscape format)

* License

  GPL v2+

* Example

  #+begin_src sh
    w3m -cookie -load-cookies=./cookies.txt -user-agent='Mozilla/5.0 (X11; Linux i686; rv:30.0) Gecko/20100101 Firefox/30.0' 'https://mail.google.com'
  #+end_src

* Netscape format
  The layout of Netscape's cookies.txt file is such that each line contains one name-value pair.

  An example cookies.txt file may have an entry that looks like this:
  #+begin_example
    .netscape.com   TRUE   /   FALSE   946684799   NETSCAPE_ID   100103
  #+end_example

  Each line represents a single piece of stored information. A tab is inserted between each of the fields.

  From left-to-right, here is what each field represents:

+ domain

  The domain that created AND that can read the variable.
+ flag

  A TRUE/FALSE value indicating if all machines within a given domain can access the variable. This value is set automatically by the browser, depending on the value you set for domain.
+ path

  The path within the domain that the variable is valid for.
+ secure

  A TRUE/FALSE value indicating if a secure connection with the domain is needed to access the variable.
+ expiration

  The UNIX time that the variable will expire on. UNIX time is defined as the number of seconds since Jan 1, 1970 00:00:00 GMT.
+ name

  The name of the variable.
+ value

  The value of the variable.

* Referenced
[[https://unix.stackexchange.com/a/210282][Format of cookies when using wget]]

[[http://www.cookiecentral.com/faq/][The Unofficial Cookie FAQ]]

[[https://github.com/Homebrew/homebrew-core][Homebrew]]

* Todo

  use getopt to parse arguments
